name: Feature request
description: Suggest new or updated features to include in FlaskBank.
title: "Suggest a new feature"
labels: ["Unreviewed", "Enhancement"]
assignees: "DefinetlyNotAI"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/DefinetlyNotAI/FlaskBank/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) for duplicate or closed feature requests
          required: true
        - label: I would like to contribute this request (Optional).
          required: false
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Provide detailed information for what we should add, including relevant links to prior art, screenshots, or live demos whenever possible.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and context
      description: Tell us why this change is needed or helpful, and what problems it may help solve.
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: What is the priority for implementing this idea?
      multiple: false
      options:
        - High
        - Normal
        - Low
    validations:
      required: true
